server:
  port: 8888
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AuthDb;encrypt=false;trustServerCertificate=true
    username: sa
    password: 123456aA@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    open-in-view: false

    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE
jwt:
  secret: 7f3c2d9a8b6e5f4a1c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0
  expiration: 3600000